// ============================================================
//  Germany Jobs Portal — 10 Lakh (1,000,000) Job Pages
//  Country: Germany | Schema: JobPosting JSON-LD
// ============================================================

const COUNTRY = {
  name: "Germany",
  sameAs: "https://en.wikipedia.org/wiki/Germany",
  addressCountry: "DE",
};

// ─── ALL COMPANIES (1,000 jobs each = 1,000,000 total) ───────────────────────
const COMPANIES = [
  // User-specified companies
  "Netflix",
  "Delta Airlines",
  "Southwest Airlines",
  "American Airlines",
  "Tesla",
  "Apple",
  "Amazon",
  "Google",
  "Disney",
  "United Airlines",
  "Wayfair",
  "Starbucks",
  "Walmart",
  "American Express",
  "Walgreens",
  "CostCo",
  "Wells Fargo",
  "Aetna",
  "Twitter",
  "PepsiCo",
  "Spirit Airlines",
  "CVS",
  "Hobby Lobby",
  "Home Depot",
  "Target",
  "Yelp",
  "Crocs",
  "Xbox",
  "Dell",
  "Anthem",
  "Sam's Club",
  "LabCorp",
  "TTEC",
  "Polaris",
  "UCHealth",
  "Smith and Wesson",
  "Hulu",
  "NDT",
  "CrunchyRoll",
  "Eddie Bauer",
  "USPC",
  "JetBlue Airlines",
  "UPS",
  "Chewy",
  "Alaska Airlines",
  "Allegiant Air",
  "Avelo Airlines",
  "Breeze Airways",
  "Eastern Airlines",
  "Frontier Airlines",
  "Hawaiian Airlines",
  "Sun Country Airlines",
  "Microsoft",
  "Meta",
  "Uber",
  "Lyft",
  "Airbnb",
  "Shopify",
  "Salesforce",
  "Adobe",
  "Zoom",
  "Slack",
  "Spotify",
  "Twitch",
  "Pinterest",
  "Snap",
  "TikTok",
  "ByteDance",
  "Nvidia",
  "Intel",
  "AMD",
  "Qualcomm",
  "Broadcom",
  "Cisco",
  "Oracle",
  "SAP",
  "IBM",
  "Accenture",
  "Deloitte",
  "PwC",
  "KPMG",
  "EY",
  "McKinsey",
  "BCG",
  "Bain",
  "Goldman Sachs",
  "JPMorgan Chase",
  "Morgan Stanley",
  "Bank of America",
  "Citigroup",
  "HSBC",
  "Deutsche Bank",
  "Siemens",
  "Volkswagen",
  "BMW",
  "Mercedes-Benz",
  "Bosch",
  "Allianz",
  "Lufthansa",
  "BASF",
  "Bayer",
  "Adidas",
  "Puma",
  "Hugo Boss",
  "Zalando",
  "Rocket Internet",
  "DeliveryHero",
  "HelloFresh",
  "N26",
  "Wirecard",
  "TeamViewer",
  "Celonis",
  "Personio",
  "Flixbus",
  "Auto1 Group",
  "AboutYou",
  "Trivago",
  "Xing",
  "ImmobilienScout24",
  "Check24",
  "Otto Group",
  "Bertelsmann",
  "ProSiebenSat1",
  "Axel Springer",
  "Burda",
  "Hubert Burda Media",
  "Ringier",
  "Springer Nature",
  "Thieme",
  "Wolters Kluwer DE",
  "Haufe Group",
  "Heise Medien",
  "T-Systems",
  "Deutsche Telekom",
  "Vodafone DE",
  "O2 Germany",
  "1&1",
  "Ionos",
  "Hetzner",
  "Strato",
  "United Internet",
  "Web.de",
  "GMX",
  "Freenet",
  "Netzsch",
  "Wacker Chemie",
  "Henkel",
  "Merck KGaA",
  "Fresenius",
  "Fresenius Medical Care",
  "Rhoen-Klinikum",
  "Helios Kliniken",
  "DHL",
  "DB Schenker",
  "Hermes Germany",
  "GLS Germany",
  "BioNTech",
  "CureVac",
  "Evotec",
  "Morphosys",
  "Heidelberg Materials",
  "ThyssenKrupp",
  "Salzgitter",
  "Klöckner",
  "Linde",
  "Air Liquide DE",
  "Drägerwerk",
  "Trumpf",
  "Kuka",
  "Festo",
  "Schäffler",
  "Continental",
  "ZF Friedrichshafen",
  "Mahle",
  "Knorr-Bremse",
  "Wabco DE",
  "Hella",
  "Osram",
  "Diehl",
  "Rheinmetall",
  "MTU Aero Engines",
  "Airbus DE",
  "Rolls-Royce DE",
  "Liebherr",
  "Claas",
  "Agco DE",
  "Fendt",
  "Krone",
  "Rauch",
  "Horsch",
  "Amazone",
  "Rewe Group",
  "Edeka",
  "Aldi",
  "Lidl",
  "Schwarz Group",
  "Penny",
  "Netto",
  "Norma",
  "Kaufland",
  "Real DE",
  "Rossmann",
  "dm-drogerie markt",
  "Müller",
  "Deichmann",
  "C&A",
  "H&M DE",
  "Zara DE",
  "Mango DE",
  "Esprit",
  "Tom Tailor",
  "Gerry Weber",
  "Takko Fashion",
  "KiK",
  "New Yorker",
  "Ernsting's family",
  "Breuninger",
  "Karstadt",
  "Galeria",
  "MediaMarkt",
  "Saturn",
  "Expert DE",
  "Euronics",
  "Conrad",
  "Reichelt Elektronik",
  "Thalia",
  "Weltbild",
  "Hugendubel",
  "Orell Füssli DE",
  "Westermann",
  "Klett",
  "Cornelsen",
  "Ravensburger",
  "Lego DE",
  "Playmobil",
  "Schleich",
  "Bruder",
  "Noch",
  "Märklin",
  "Roco",
  "Piko",
  "Faller",
  "Vollmer",
  "Kibri",
  "Preiser",
  "Auhagen",
  "Wiking",
  "Herpa",
  "Busch",
  "Woodland Scenics DE",
  "Gaugemaster DE",
  "Athearn DE",
  "Atlas Model Railroad DE",
  "Bachmann DE",
  "Walthers DE",
  "InterRail",
  "Eurail",
  "Deutsche Bahn",
  "Flughafengesellschaft",
  "Munich Airport",
  "Frankfurt Airport",
  "Hamburg Airport",
  "Dusseldorf Airport",
  "Berlin Brandenburg Airport",
  "Cologne Bonn Airport",
  "Stuttgart Airport",
  "Nuremberg Airport",
  "Bremen Airport",
  "Hannover Airport",
  "Leipzig Halle Airport",
  "Dresden Airport",
  "Erfurt Weimar Airport",
  "Friedrichshafen Airport",
  "Weeze Airport",
  "Paderborn Lippstadt Airport",
  "Kassel Calden Airport",
  "Hahn Airport",
  "Zweibrücken Airport",
  "Memmingen Airport",
  "Rostock Laage Airport",
  "Heringsdorf Airport",
  "Heide Büsum Airport",
  "Lübeck Airport",
  "Kiel Airport",
  "Flensburg Airport",
  "Sylt Airport",
  "Borkum Airport",
  "Norderney Airport",
  "Baltrum Airport",
  "Langeoog Airport",
  "Spiekeroog Airport",
  "Wangerooge Airport",
  "Juist Airport",
  "Helgoland Airport",
  "Comdirect",
  "ING-DiBa",
  "DKB Bank",
  "Sparkasse",
  "Volksbank",
  "Commerzbank",
  "HypoVereinsbank",
  "Postbank",
  "Targobank",
  "Norisbank",
  "Consorsbank",
  "Flatex",
  "Trade Republic",
  "Scalable Capital",
  "Justtrade",
  "Smartbroker",
  "Onvista",
  "Degiro DE",
  "Etoro DE",
  "IG Markets DE",
  "CMC Markets DE",
  "XTB DE",
  "Saxo Bank DE",
  "Interactive Brokers DE",
  "Swissquote DE",
  "Lynx Broker",
  "Maxblue",
  "S Broker",
  "DAB BNP Paribas",
  "ebase",
  "FFB",
  "FIL Fondsbank",
  "Union Investment",
  "DWS",
  "Deka",
  "Flossbach von Storch",
  "Berenberg",
  "Hauck Aufhäuser Lampe",
  "Metzler",
  "Donner Reuschel",
  "Bankhaus Ellwanger Geiger",
  "Warburg Bank",
  "Bethmann Bank",
  "Fürst Fugger Privatbank",
  "Merck Finck",
  "Quirin Privatbank",
  "Siemens Financial Services",
  "BMW Financial Services",
  "Volkswagen Financial Services",
  "Mercedes-Benz Financial Services",
  "Opel Financial Services",
  "Ford Financial Services DE",
  "Renault Financial Services DE",
  "PSA Financial Services DE",
  "Stellantis Financial DE",
  "Hyundai Financial DE",
  "Kia Financial DE",
  "Toyota Financial DE",
  "Honda Financial DE",
  "Nissan Financial DE",
  "Mitsubishi Financial DE",
  "Mazda Financial DE",
  "Subaru Financial DE",
  "Suzuki Financial DE",
  "Dacia Financial DE",
  "Seat Financial DE",
  "Skoda Financial DE",
  "Porsche Financial DE",
  "Audi Financial DE",
  "Lamborghini Financial DE",
  "Bentley Financial DE",
  "Rolls-Royce Financial DE",
  "Bugatti Financial DE",
  "Pagani Financial DE",
  "Koenigsegg Financial DE",
  "Rimac Financial DE",
  "Pininfarina Financial DE",
  "Italdesign Financial DE",
  "Giugiaro Financial DE",
  "Bertone Financial DE",
  "Zagato Financial DE",
  "Touring Financial DE",
  "Ghia Financial DE",
  "Vignale Financial DE",
  "Frua Financial DE",
  "Michelotti Financial DE",
  "Allemano Financial DE",
  "Boneschi Financial DE",
  "Castagna Financial DE",
  "Fissore Financial DE",
  "Moretti Financial DE",
  "Neri Financial DE",
  "Orlandi Financial DE",
  "Savio Financial DE",
  "Scioneri Financial DE",
  "Scioneri Motor DE",
  "Rometsch Financial DE",
  "Baur Financial DE",
  "Autenrieth Financial DE",
  "Binz Financial DE",
  "Miesen Financial DE",
  "Welsch Financial DE",
  "Schaaf Financial DE",
  "Pollmann Financial DE",
  "Rappold Financial DE",
  "Horcher Financial DE",
  "Stolle Financial DE",
  "Gläser Financial DE",
  "Ramseier Financial DE",
  "Stutz Financial DE",
  "Hebmüller Financial DE",
  "Rau Financial DE",
  "Papler Financial DE",
  "Wendler Financial DE",
  "Deutsch Financial DE",
  "Bauer Financial DE",
  "Fischer Financial DE",
  "Müller Financial DE",
  "Schmidt Financial DE",
  "Schneider Financial DE",
  "Wagner Financial DE",
  "Weber Financial DE",
  "Mayer Financial DE",
  "Hoffmann Financial DE",
  "Schulz Financial DE",
  "Koch Financial DE",
  "Becker Financial DE",
  "Richter Financial DE",
  "Klein Financial DE",
  "Wolf Financial DE",
  "Schäfer Financial DE",
  "König Financial DE",
  "Walter Financial DE",
  "Peters Financial DE",
  "Lang Financial DE",
  "Braun Financial DE",
  "Krause Financial DE",
  "Fuchs Financial DE",
  "Meyer Financial DE",
  "Weiß Financial DE",
  "Zimmermann Financial DE",
  "Krüger Financial DE",
  "Hartmann Financial DE",
  "Lange Financial DE",
  "Werner Financial DE",
  "Schmid Financial DE",
  "Lehmann Financial DE",
  "Frank Financial DE",
  "Huber Financial DE",
  "Lutz Financial DE",
  "Krämer Financial DE",
  "Herrmann Financial DE",
  "Schwarz Financial DE",
  "Maier Financial DE",
  "Günther Financial DE",
  "Brandt Financial DE",
  "Ernst Financial DE",
  "Ludwig Financial DE",
  "Schubert Financial DE",
  "Kramer Financial DE",
  "Simon Financial DE",
  "Groß Financial DE",
  "Dietrich Financial DE",
  "Neuhaus Financial DE",
  "Pohl Financial DE",
  "Franke Financial DE",
  "Heinrich Financial DE",
  "Kühn Financial DE",
  "Albrecht Financial DE",
  "Busch Financial DE",
  "Vogt Financial DE",
  "Bergmann Financial DE",
  "Schumacher Financial DE",
  "Engel Financial DE",
  "Graf Financial DE",
  "Frey Financial DE",
  "Hahn Financial DE",
  "Sommer Financial DE",
  "Roth Financial DE",
  "Kiefer Financial DE",
  "Voigt Financial DE",
  "Kaufmann Financial DE",
  "Stein Financial DE",
  "Berg Financial DE",
  "Pfeiffer Financial DE",
  "Ritter Financial DE",
  "Wirth Financial DE",
  "Sander Financial DE",
  "Langer Financial DE",
  "Horn Financial DE",
  "Winter Financial DE",
  "Kuhn Financial DE",
  "Schrader Financial DE",
  "Haas Financial DE",
  "Moser Financial DE",
  "Böhm Financial DE",
  "Kern Financial DE",
  "Bremer Financial DE",
  "Paul Financial DE",
  "Ziegler Financial DE",
  "Büttner Financial DE",
  "Hesse Financial DE",
  "Lorenz Financial DE",
  "Kroll Financial DE",
  "Stoll Financial DE",
  "Weiss Financial DE",
  "Krug Financial DE",
  "Reich Financial DE",
  "Beckmann Financial DE",
  "Baumann Financial DE",
  "Busse Financial DE",
  "Franken Financial DE",
  "Freund Financial DE",
  "Gärtner Financial DE",
  "Geiger Financial DE",
  "Gerber Financial DE",
  "Glaser Financial DE",
  "Götz Financial DE",
  "Grimm Financial DE",
  "Grün Financial DE",
  "Günter Financial DE",
  "Hacker Financial DE",
  "Hansen Financial DE",
  "Harder Financial DE",
  "Haupt Financial DE",
  "Heim Financial DE",
  "Heise Financial DE",
  "Held Financial DE",
  "Heller Financial DE",
  "Henning Financial DE",
  "Hermann Financial DE",
  "Hess Financial DE",
  "Hofmann Financial DE",
  "Holz Financial DE",
  "Hummel Financial DE",
  "Jäger Financial DE",
  "Jahn Financial DE",
  "Kaiser Financial DE",
  "Keller Financial DE",
  "Kiesel Financial DE",
  "Kilian Financial DE",
  "Kirsch Financial DE",
  "Knapp Financial DE",
  "Knopp Financial DE",
  "Köhler Financial DE",
  "Kopp Financial DE",
  "Kraft Financial DE",
  "Kremer Financial DE",
  "Kübler Financial DE",
  "Kunze Financial DE",
  "Lenz Financial DE",
  "Link Financial DE",
  "Lipp Financial DE",
  "Löffler Financial DE",
  "Loth Financial DE",
  "Lux Financial DE",
  "Manns Financial DE",
  "Mark Financial DE",
  "Martin Financial DE",
  "Maurer Financial DE",
  "Metz Financial DE",
  "Michel Financial DE",
  "Möller Financial DE",
  "Nagel Financial DE",
  "Naumann Financial DE",
  "Neumann Financial DE",
  "Nickel Financial DE",
  "Nikolaus Financial DE",
  "Noll Financial DE",
  "Ober Financial DE",
  "Oehler Financial DE",
  "Otto Financial DE",
  "Paulus Financial DE",
  "Pawlik Financial DE",
  "Philipp Financial DE",
  "Pohle Financial DE",
  "Preuss Financial DE",
  "Prinz Financial DE",
  "Probst Financial DE",
  "Pröhl Financial DE",
  "Propst Financial DE",
  "Quast Financial DE",
  "Rabe Financial DE",
  "Rauch Financial DE",
  "Reibold Financial DE",
  "Reimer Financial DE",
  "Reuter Financial DE",
  "Riedl Financial DE",
  "Riedner Financial DE",
  "Rietschel Financial DE",
  "Rinke Financial DE",
  "Röder Financial DE",
  "Rohde Financial DE",
  "Rohr Financial DE",
  "Roller Financial DE",
  "Rommel Financial DE",
  "Rose Financial DE",
  "Roth Financial DE",
  "Rothe Financial DE",
  "Ruf Financial DE",
  "Rupp Financial DE",
  "Sack Financial DE",
  "Sauer Financial DE",
  "Schäffer Financial DE",
  "Schall Financial DE",
  "Schellenberg Financial DE",
  "Scherer Financial DE",
  "Schilling Financial DE",
  "Schindler Financial DE",
  "Schlegel Financial DE",
  "Schlosser Financial DE",
  "Schlüter Financial DE",
  "Schmal Financial DE",
  "Schmalz Financial DE",
  "Schmitt Financial DE",
  "Schmitz Financial DE",
  "Schreiber Financial DE",
  "Schröder Financial DE",
  "Schuhmacher Financial DE",
  "Schulte Financial DE",
  "Schultz Financial DE",
  "Schumacher Financial DE",
  "Schuster Financial DE",
  "Seeger Financial DE",
  "Seidel Financial DE",
  "Seifert Financial DE",
  "Siegel Financial DE",
  "Siegert Financial DE",
  "Sievers Financial DE",
  "Specht Financial DE",
  "Spengler Financial DE",
  "Sperber Financial DE",
  "Springmann Financial DE",
  "Stahl Financial DE",
  "Stark Financial DE",
  "Stefan Financial DE",
  "Steger Financial DE",
  "Stern Financial DE",
  "Stock Financial DE",
  "Strasser Financial DE",
  "Straub Financial DE",
  "Strauch Financial DE",
  "Strauß Financial DE",
  "Streicher Financial DE",
  "Streit Financial DE",
  "Strobel Financial DE",
  "Stroh Financial DE",
  "Strohmayer Financial DE",
  "Struck Financial DE",
  "Stüber Financial DE",
  "Stumm Financial DE",
  "Stumpe Financial DE",
  "Sturm Financial DE",
  "Suhr Financial DE",
  "Süßmann Financial DE",
  "Sutter Financial DE",
  "Tanner Financial DE",
  "Thomas Financial DE",
  "Thomsen Financial DE",
  "Tiedemann Financial DE",
  "Tillmann Financial DE",
  "Timm Financial DE",
  "Tischer Financial DE",
  "Tönnis Financial DE",
  "Trapp Financial DE",
  "Trautmann Financial DE",
  "Treffer Financial DE",
  "Trenkle Financial DE",
  "Trilk Financial DE",
  "Tripp Financial DE",
  "Trojan Financial DE",
  "Trost Financial DE",
  "Uhl Financial DE",
  "Uhlich Financial DE",
  "Ulrich Financial DE",
  "Valentin Financial DE",
  "Vetter Financial DE",
  "Vogel Financial DE",
  "Volkmann Financial DE",
  "Vollmer Financial DE",
  "Volz Financial DE",
  "Wagenknecht Financial DE",
  "Wahle Financial DE",
  "Walther Financial DE",
  "Wander Financial DE",
  "Warnecke Financial DE",
  "Warnke Financial DE",
  "Weigel Financial DE",
  "Weil Financial DE",
  "Weise Financial DE",
  "Weißenberg Financial DE",
  "Wendling Financial DE",
  "Wengler Financial DE",
  "Wenzel Financial DE",
  "Wenz Financial DE",
  "Westphal Financial DE",
  "Wiese Financial DE",
  "Wild Financial DE",
  "Wilde Financial DE",
  "Wilke Financial DE",
  "Willms Financial DE",
  "Winkler Financial DE",
  "Witt Financial DE",
  "Witte Financial DE",
  "Wittig Financial DE",
  "Wöllner Financial DE",
  "Wolff Financial DE",
  "Wollmann Financial DE",
  "Wolter Financial DE",
  "Worms Financial DE",
  "Wulf Financial DE",
  "Zahn Financial DE",
  "Zanker Financial DE",
  "Zeck Financial DE",
  "Zeidler Financial DE",
  "Zeller Financial DE",
  "Ziegler Financial DE",
  "Zorn Financial DE",
  "Zuber Financial DE",
];

const JOBS_PER_COMPANY = 1000;
const TOTAL_JOBS = COMPANIES.length * JOBS_PER_COMPANY;

// ─── GERMAN CITIES / LOCATIONS ───────────────────────────────────────────────
const DE_CITIES = [
  "Berlin",
  "Hamburg",
  "Munich",
  "Cologne",
  "Frankfurt",
  "Stuttgart",
  "Düsseldorf",
  "Leipzig",
  "Dortmund",
  "Essen",
  "Bremen",
  "Dresden",
  "Hanover",
  "Nuremberg",
  "Duisburg",
  "Bochum",
  "Wuppertal",
  "Bielefeld",
  "Bonn",
  "Münster",
  "Karlsruhe",
  "Mannheim",
  "Augsburg",
  "Wiesbaden",
  "Mönchengladbach",
  "Gelsenkirchen",
  "Aachen",
  "Braunschweig",
  "Kiel",
  "Chemnitz",
  "Magdeburg",
  "Halle",
  "Freiburg",
  "Krefeld",
  "Mainz",
  "Lübeck",
  "Erfurt",
  "Oberhausen",
  "Rostock",
  "Kassel",
  "Hagen",
  "Potsdam",
  "Saarbrücken",
  "Hamm",
];

// ─── SALARY RANGES (in EUR per month) ────────────────────────────────────────
const SALARY_RANGES = [
  { min: 2500, max: 3500 },
  { min: 3500, max: 5000 },
  { min: 5000, max: 7500 },
  { min: 7500, max: 10000 },
  { min: 10000, max: 15000 },
  { min: 15000, max: 20000 },
  { min: 20000, max: 30000 },
  { min: 2500, max: 4500 },
  { min: 4000, max: 6000 },
  { min: 6000, max: 9000 },
];

// ─── JOB TITLE TEMPLATES ─────────────────────────────────────────────────────
const TITLE_TEMPLATES = [
  "{company} Remote Jobs (Work From Home) {salMin} To {salMax} EUR",
  "{company} Customer Support Jobs Work From Home Germany",
  "{company} Data Entry Jobs Only - {salMin} To {salMax}/ Monthly",
  "{company} Work From Home Jobs - {salMin} To {salMax} EUR Monthly Salary",
  "{company} Remote Customer Service Representative (Germany)",
  "{company} Virtual Assistant Jobs Germany {salMin}-{salMax}",
  "{company} Online Jobs Germany - No Experience Required",
  "{company} Data Analyst Work From Home Jobs {salMin} To {salMax}",
  "{company} Remote Software Engineer Jobs Germany 2025",
  "{company} Chat Support Agent Work From Home {salMin} To {salMax}",
  "{company} Social Media Manager Remote Jobs Germany",
  "{company} Content Moderator Jobs Work From Home {salMin}",
  "{company} Remote Accounting Jobs Germany - {salMin} To {salMax}",
  "{company} Night Shift Work From Home Jobs {salMin} To {salMax}",
  "{company} Part Time Remote Jobs Germany {salMin} Monthly",
  "{company} Email Support Jobs Work From Home {salMin} To {salMax}",
  "{company} Remote Marketing Jobs Germany {salMin} To {salMax}",
  "{company} Technical Support Specialist Work From Home",
  "{company} HR Remote Jobs Germany {salMin} To {salMax} Monthly",
  "{company} Project Manager Work From Home Germany {salMin}",
  "{company} Remote QA Tester Jobs Germany {salMin} To {salMax}",
  "{company} Graphic Designer Work From Home {salMin} To {salMax}",
  "{company} Video Editor Remote Jobs Germany {salMin} Monthly",
  "{company} Remote Sales Representative Germany {salMin} To {salMax}",
  "{company} Transcriptionist Jobs Work From Home Germany",
  "{company} Remote Business Analyst Jobs Germany {salMin} To {salMax}",
  "{company} UI/UX Designer Work From Home Germany {salMin}",
  "{company} Remote Product Manager Jobs Germany {salMin} To {salMax}",
  "{company} Work From Home Admin Assistant Jobs Germany",
  "{company} Remote Copywriter Jobs Germany {salMin} To {salMax}",
  "{company} Telehealth Nurse Jobs Work From Home Germany",
  "{company} Remote Financial Analyst Jobs Germany {salMin} To {salMax}",
  "{company} Online Tutor Jobs Germany {salMin} To {salMax} Monthly",
  "{company} Remote IT Support Jobs Germany No Experience",
  "{company} Work From Home SEO Specialist Jobs Germany {salMin}",
  "{company} Remote Legal Assistant Jobs Germany {salMin} To {salMax}",
  "{company} Digital Marketing Specialist Work From Home {salMin}",
  "{company} Remote Bookkeeper Jobs Germany {salMin} To {salMax}",
  "{company} Customer Success Manager Work From Home Germany",
  "{company} Remote Operations Analyst Jobs Germany {salMin} To {salMax}",
];

// ─── JOB DESCRIPTIONS ────────────────────────────────────────────────────────
const DESCRIPTIONS = [
  `Join our growing remote team! We are looking for talented individuals based in Germany to work with {company}. This is a fully remote position with competitive pay.

**What You'll Do:**
- Handle customer inquiries via email, chat, and phone
- Process data accurately and efficiently
- Coordinate with team members across different time zones
- Meet daily and weekly performance targets
- Provide excellent service to our global customers

**Requirements:**
- Strong English and/or German communication skills (written and verbal)
- Stable internet connection (minimum 10 Mbps)
- Dedicated workspace at home
- Computer or laptop (Windows 10 or Mac OS)
- Available to work full-time (40 hours/week)

**Benefits:**
- 100% Work From Home
- Health insurance (Gesetzliche Krankenversicherung)
- 30 days paid vacation (Urlaubsanspruch)
- Paid sick leave
- Internet allowance
- Equipment provided
- Career growth opportunities

Apply now and start your remote career with {company}!`,

  `{company} is hiring remote workers from Germany! No prior experience needed — full training provided. Start earning {salMin} to {salMax} EUR per month from the comfort of your home.

**Position Highlights:**
- Permanent work-from-home setup
- Fixed dayshift / midshift / nightshift schedules available
- Weekends off (depending on account)
- Permanent contract after probation period
- Fast-track promotion for top performers

**Day-to-Day Tasks:**
- Respond to customer concerns promptly
- Document interactions in company CRM
- Escalate complex issues to senior agents
- Maintain quality scores above 95%
- Attend virtual team meetings and training

**Minimum Qualifications:**
- At least 18 years old
- High school diploma or equivalent (Abitur or Hauptschulabschluss)
- Basic computer literacy
- Willing to work shifting schedules
- Has own laptop/desktop and reliable internet

**Compensation Package:**
- Basic Pay: {salMin} - {salMax} EUR/month
- Language allowance
- Performance incentives
- Health insurance from Day 1
- Life insurance`,

  `We are expanding our Germany-based remote workforce at {company}! This is your chance to join a world-class company and build a rewarding career — all from home.

**About the Role:**
As part of our global team, you'll support operations, customers, or business functions depending on your department. Roles available in customer service, data operations, tech support, finance, HR, and more.

**Core Responsibilities:**
- Execute assigned tasks with accuracy and efficiency
- Communicate professionally with internal and external stakeholders
- Follow company processes and quality guidelines
- Continuously improve skills through training and feedback
- Represent {company} values in every interaction

**Who We're Looking For:**
- German residents with right to work in Germany
- Self-motivated and reliable individuals
- Good internet connection and home office setup
- Fluent in German or English (bilingual preferred)
- Comfortable with digital tools and remote collaboration

**What {company} Offers:**
- Salary: {salMin} to {salMax} EUR per month
- Remote work allowance
- 30 days annual leave (Jahresurlaub)
- Betriebliche Altersvorsorge (company pension)
- Weiterbildungsangebote (training opportunities)
- Flexible working hours`,
];

// ─── JOB TYPES ───────────────────────────────────────────────────────────────
const JOB_TYPES = [
  "FULL_TIME",
  "PART_TIME",
  "CONTRACTOR",
  "TEMPORARY",
  "FULL_TIME",
  "FULL_TIME",
  "FULL_TIME",
  "FULL_TIME",
  "PART_TIME",
  "FULL_TIME",
];

// ─── GENERATE A SINGLE JOB ───────────────────────────────────────────────────
function getJob(id) {
  if (id < 1 || id > TOTAL_JOBS) return null;

  const companyIndex = Math.floor((id - 1) / JOBS_PER_COMPANY);
  const jobIndexInCompany = (id - 1) % JOBS_PER_COMPANY;
  const company = COMPANIES[companyIndex];

  const salaryRange = SALARY_RANGES[jobIndexInCompany % SALARY_RANGES.length];
  const salMin = salaryRange.min.toLocaleString();
  const salMax = salaryRange.max.toLocaleString();

  const titleTemplate = TITLE_TEMPLATES[jobIndexInCompany % TITLE_TEMPLATES.length];
  const title = titleTemplate
    .replace(/{company}/g, company)
    .replace(/{salMin}/g, salMin)
    .replace(/{salMax}/g, salMax);

  const city = DE_CITIES[jobIndexInCompany % DE_CITIES.length];
  const isRemote = jobIndexInCompany % 3 !== 0;

  const descTemplate = DESCRIPTIONS[jobIndexInCompany % DESCRIPTIONS.length];
  const description = descTemplate
    .replace(/{company}/g, company)
    .replace(/{salMin}/g, salMin)
    .replace(/{salMax}/g, salMax);

  const jobType = JOB_TYPES[jobIndexInCompany % JOB_TYPES.length];

  const baseDate = new Date("2025-01-01");
  baseDate.setDate(baseDate.getDate() + (id % 180));
  const datePosted = baseDate.toISOString().split("T")[0];

  const validDate = new Date(baseDate);
  validDate.setDate(validDate.getDate() + 90);
  const validThrough = validDate.toISOString().split("T")[0];

  return {
    id,
    title,
    company,
    salary: `€${salMin} - €${salMax}/month`,
    salaryMin: salaryRange.min,
    salaryMax: salaryRange.max,
    city,
    location: `${city}, Germany`,
    isRemote,
    description,
    jobType,
    datePosted,
    validThrough,
    country: COUNTRY,
  };
}

module.exports = { TOTAL_JOBS, COMPANIES, JOBS_PER_COMPANY, COUNTRY, getJob };
